name: Rust
on:
  push:
    branches: [ "main" ]
    tags:
      - '*'

  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: checkout
      uses: actions/checkout@v4
  
    - name: build 
      uses: houseabsolute/actions-rust-cross@v0
      with:
        command: "build"
        target: x86_64-pc-windows-msvc 
        toolchain: nightly
        args: "--locked --manifest-path=Patching_AmsiScanBuffer/Cargo.toml"
        strip: false

    - name: list files
      run:  gci -recurse

    - name: upload artifact 
      uses: actions/upload-artifact@v3
      with:
        name: Patching_####ScanBuffer.dll
        path: Patching_AmsiScanBuffer\target\x86_64-pc-windows-msvc\debug\AMSIBypassDLL.dll
    
    - name: release
      uses: ncipollo/release-action@v1
      with:
        path: Patching_AmsiScanBuffer\target\x86_64-pc-windows-msvc\debug\AMSIBypassDLL.dll
