name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: change directory
    - run: cd Patching_AmsiScanBuffer

    - name: Build
    - run: cargo build --verbose
    
    - uses: actions/upload-artifact@v3
      with:
        name: Patching_****ScanBuffer.dll
        path: target/debug/AMSIBypassDLL.dll
