name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
    - uses: actions/checkout@v4
    
    - name: Build
    - run: cargo build --verbose --manifest-path=Patching_AmsiScanBuffer/Cargo.toml
    
    - uses: actions/upload-artifact@v3
    - name: upload artifact 
      with:
        name: Patching_****ScanBuffer.dll
        path: Patching_AmsiScanBuffer/target/debug/AMSIBypassDLL.dll
